services:
  shortlinksservice:
    image: shortlinksservice
    build:
      context: .
      dockerfile: ShortLinksService/Dockerfile
  mongodb: 
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"